export const DIVISION_FIELDS = {
  NAME: 'name',
  LEVEL: 'level',
  COLLABORATORS: 'collaborators',
  PARENT_ID: 'parentId',
  AMBASSADOR_NAME: 'ambassadorName',
  CREATED_AT: 'createdAt',
  UPDATED_AT: 'updatedAt',
} as const;

export const SEARCHABLE_FIELDS = [
  DIVISION_FIELDS.NAME,
  DIVISION_FIELDS.AMBASSADOR_NAME,
];

export const FILTERABLE_FIELDS = [
  DIVISION_FIELDS.NAME,
  DIVISION_FIELDS.LEVEL,
  DIVISION_FIELDS.COLLABORATORS,
  DIVISION_FIELDS.PARENT_ID,
  DIVISION_FIELDS.AMBASSADOR_NAME,
  DIVISION_FIELDS.CREATED_AT,
];
